const products = [
    {
        id:1,
        name: "Girl's Top",
        image: "./images/p1.jpg",
        price: 400,
        oldPrice: 500,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:2,
        name: "Boy's Suit",
        image: "./images/p2.jpg",
        price: 3199,
        oldPrice: 3999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:3,
        name: "Girl's Lower",
        image: "./images/p3.jpg",
        price: 400,
        oldPrice: 500,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:4,
        name: "Boy's Suit",
        image: "./images/p4.jpg",
        price: 3199,
        oldPrice: 3999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:5,
        name: "Girl's T-shirt",
        image: "./images/p5.jpg",
        price: 400,
        oldPrice: 500,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:6,
        name: "Girl's Shirt",
        image: "./images/p6.jpg",
        price: 3999,
        oldPrice: 4999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:7,
        name: "Women Sweatshirt ",
        image: "./images/p7.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:8,
        name: "Men Casual Shirt",
        image: "./images/p8.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:9,
        name: "Women High Neck Sweater",
        image: "./images/p9.jpg",
        price: 639,
        oldPrice: 799,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:10,
        name: "Men Casual Shirt",
        image: "./images/p10.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:11,
        name: "Women White Jeans",
        image: "./images/p11.jpg",
        price: 639,
        oldPrice: 799,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:12,
        name: "Men Casual Shirt",
        image: "./images/p12.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },

    {
        id:13,
        name: "Men White T-Shirt",
        image: "./images/p13.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
      {
        id:14,
        name: "Women t-Shirt Full Sleeve",
        image: "./images/p14.jpg",
        price: 399,
        oldPrice: 499,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
 
    {
        id:15,
        name: "Men Light Black Jeans",
        image: "./images/p15.jpg",
        price: 799,
        oldPrice: 999,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    {
        id:16,
        name: "Women's Jeans",
        image: "./images/p16.jpg",
        price: 639,
        oldPrice: 799,
        desc:  "ipsum dolor sit amet consectetur adipisicing elit. Animi vel, eum eius et error assumenda tempora laboriosam recusandae sequi voluptates.",
    },
    
]